# Generated by Django 4.2.11 on 2024-04-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meugame", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="game", name="description",),
    ]
